name: Maven Deploy

on:
  workflow_run:
    workflows: ["Run Tests"]
    branches:
      - master
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: app-jar
          path: target/

      - name: Deploy to Dev or Prod
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER: ${{ github.ref == 'refs/heads/master' && secrets.PROD_SERVER || secrets.DEV_SERVER }}
          USER: ${{ github.ref == 'refs/heads/master' && secrets.PROD_USER || secrets.DEV_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem $USER@$SERVER << 'EOF'
            cd /path/to/your/app
            java -jar target/*.jar &
          EOF
