name: Java CI with Maven

on:
  workflow_call:

jobs:
  build:
    name: Setting Up Java and Maven
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-timeout=10s --health-retries=3

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: |
        cd backend
        mvn -B package --file pom.xml -Ddb.url=jdbc:mysql://localhost:3306/test_db -Ddb.username=root -Ddb.password=root
      
  test:
    name: Running Test Cases
    runs-on: ubuntu-latest
    needs: [build]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-timeout=10s --health-retries=3

    steps:
      - name: Checkout code again
        uses: actions/checkout@v4

      - name: Run test Cases
        run: mvn test -Ddb.url=jdbc:mysql://localhost:3306/test_db -Ddb.username=root -Ddb.password=root



  