name: Frontend Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/hotel-booking-frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: |
          cd frontend\hotel-booking-frontend
          npm install

      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy frontend
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "Deploying frontend..."
          cd frontend\hotel-booking-frontend
          npm run deploy
