name: Java Build with Maven

on:
  push:
    branches:
      - main
    paths:
      - "frontend/hotel-booking-frontend/**"

jobs:
  frontend-build:
    uses: ./.github/workflows/frontend-template.yml
